### ISSUE TITLE
STAN

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/bioc_git_transition#33]
master points to RELEASE_3_0; RELEASE_3_* logs are incomplete

**Comment by nturaga** [comment]
Is this only for STAN? or are there other packages which behave like this? How did the error get detected?

**Comment by nturaga** [comment]
`git svn clone --authors-file=/home/git/bioc_git_transition/R/extdata/users_db.txt file:///home/git/hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/STAN`

The initial step of the process fails because, 

`Author: r.campos not defined in /home/git/bioc_git_transition/R/extdata/users_db.txt file`

```
cd STAN
STAN$ tree
.

0 directories, 0 files
```

The reason its in RELEASE_3_0, is because that is the only `git svn fetch` which worked.

```
commit 9b53ab973d9c322663c5e814921b9956b6a55d21 (HEAD -> master, git-svn-RELEASE_3_0, RELEASE_3_0)
Author: Dan Tenenbaum <dtenenba@fhcrc.org>
Date:   Mon Oct 13 21:46:02 2014 +0000

    Creating branch for BioC 3.0 release.

    git-svn-id: file:///home/git/hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_0/madman/Rpacks/STAN@95441 bc3139a8-67e5-0310-9ffc-ced21a209358
```

**Comment by mtmorgan** [comment]
This is a consequence of our using the stale users.txt export from svn -- we used one created on Jul 17, but the (only, after 6 releases) commit of r.campos was on Jul 18. There will be similar problems for all authors who make their first commit between Jul 17 and yesterday. I'll come up with a list...

**Comment by mtmorgan** [comment]
I believe r.campos / STAN is the only one.

**Comment by nturaga** [comment]
This bug has been fixed and STAN is accessible with the correct history.
