### ISSUE TITLE
Unsupported LANG on server generate warning on client

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/bioc_git_transition#34]
https://stat.ethz.ch/pipermail/bioc-devel/2017-August/011325.html

fix?? https://stackoverflow.com/a/2510548/547331 

- edit `/etc/ssh/sshd_config` to remove AcceptEnv LANG_LC *
- or login script sets LANG=C ?

**Comment by mtmorgan** [comment]
I can reproduce in a bash shell on linux with, e.g.,

```
$ git clone git@git.bioconductor.org:packages/AnnotationHub
$ cd AnnotationHub
AnnotationHub$ LC_ALL=pt_BR.UTF-8 git pull
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "pt_BR.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Already up-to-date.
```

**Comment by vobencha** [comment]
@mtmorgan There are 2 ssh config files, one is for clients connecting to the host and the other is for the ssh daemon running on the host. To prevent clients from propagating their locale variables I've modified config file for the daemon, /etc/ssh/sshd_confg, by commenting out this line
```
AcceptEnv LANG LC_*
```
and restarted the service
```
sudo service sshd restart
```
I can now pass a different locale and not see the perl warning:
```
~/AnnotationHub >LC_ALL=pt_BR.UTF-8 git pull
Already up-to-date.
```
/etc/ssh/ssh_config is the config file for the ssh client on the host. These setting are used when ssh'ing to another machine from git.bioconductor.org. If we wanted to prevent sending locale information from the git machine we would comment out this line:
```
SendEnv LANG LC_*
```
I didn't do this because it doesn't address the question at hand and it seems to be a harmless default on the other EC2 instances. Let me know if you want this changed too.

Val

**Comment by mtmorgan** [comment]
Perfect thanks!
