### ISSUE TITLE
Can a repo collaborator push a package to bioc-git?

### ISSUE THREAD

**Issue by gabora** [Bioconductor/bioc_git_transition#40]
Dear developers, 

our group developed the CellNOptR package. The original author/maintainer of the package (cokelaer) has permission to push the package from his personal repo (cokelaer/CellNOptR) to the git@git.bioconductor.org:packages/CellNOptR.git.

I also have writing access to his repo and I registered my ssh key for bioconductor, but I cannot push to the bioconductor repo:

```
✔ {16:18}[]~/Documents/SaezGrp/LocalGitRepo/bioconductor/CellNOptR:[master|✔ ] ➭ git remote add upstream git@git.bioconductor.org:packages/CellNOptR.git
✔ {16:18}[]~/Documents/SaezGrp/LocalGitRepo/bioconductor/CellNOptR:[master|✔ ] ➭ git push upstream master
FATAL: W any packages/CellNOptR gabora DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```
Please note, that I was not a maintainer of this package before (on the SVN). 

Is there a way with the new system to give me access to push to bioc...packages/CellNOptR ?
thanks

**Comment by mtmorgan** [comment]
Please have @cokelaer send email, cc'ing you, to packages at bioconductor.org asking to give you write permissions; it is often better to have a single individual with write access to git.bioconductor.org.

**Comment by HenrikBengtsson** [comment]
> [...] it is often better to have a single individual with write access to git.bioconductor.org.

@mtmorgan, may I ask why? How is it different now with Git than in the past with Subversion where multiple users could commit/push?  If only one person can push to git.bioconductor.org, won't this force collaboration to take place elsewhere (e.g. GitHub) - where that single person has to make sure to merge and push to the git.bioconductor.org remote?  (sorry if this has already been discussed - I've been out of the loop for a while)

**Comment by mtmorgan** [comment]
@HenrikBengtsson There are two main reasons.

One is complexity. Here we have at least two repositories, on git.bioconductor.org as well as github. The challenge is to keep them all in sync, or at least not hopelessly in conflict. It seems more prudent to have one person responsible for this. I think it is not unusual for github collaboration to also work in this way, with pull requests even from close collaborators rather than direct commits. It also makes it clear who is responsible for problems that may occur on git.bioconductor.org -- the one person with write access. Some of this is echoed in the CRAN policy of a single Maintainer:, even with multiple authors. Merge conflicts seem much more common under git than svn.

The second is the additional bureaucracy, again as seen here, where git.bioconductor.org does not (yet) have a way for 'owners' to manage their own collaborations. Github (and other environments) empower the maintainer to engage as much or as little of the community as they desire.

Of course, no one has to follow my suggestions; we can arrange for multiple writers on a single repository. And the process is actually simpler than svn (where we had to ask for new user accounts from a third party) so we have actually made some progress.

**Comment by HenrikBengtsson** [comment]
Thanks for clarifying and sharing these views - it's helpful.  The analogue to CRAN submissions make sense.  

I agree, many use the model where they use pull requests (PRs) even for close collaborations.  Having Git UIs such as GitHub) for communicating (displaying and discussing) PRs is helpful.  Honestly, I'm not sure how that's can be neatly done without such interfaces.

Related to this, as long as you don't mess with the Bioconductor reserved branches, there are no restrictions to what branches you push to git.bioconductor.org, correct?  For instance, using a `develop` branch for non-released work (e.g. a package version `x.y.z-9000`).

My current approach is to treat GitHub as my go-to-root-source repository (i.e. `remote.origin.url=git@github.com:HenrikBengtsson/pkg.git`) where the `master` branch always reflects what is one Bioconductor and other branches for ongoing work that I don't want to "release" on Bioc.   Then I have a second remote set up for Bioconductor (i.e. `remote.bioc.url=git@git.bioconductor.org:packages/aroma.light.git`) such that when I do `git checkout master; git push bioc` to make a new release (`x.y.z+1`).

**Comment by mtmorgan** [comment]
Actually, there are tight restrictions on git.bioconductor.org repositories. In particular, ordinary developers can't create branches, and can't change history. These policies might change as we gain experience, but our primary concern was to provide a repository reflecting the history of released packages. This makes changing history out of the question, and creating new branches out of scope. For new branches, I don't think we have enough technical expertise to make release and devel branches behave reliably the way we require (e.g., we don't want ordinary developers creating RELEASE_3_7 before we branch-and-version-bump for RELEASE_3_7). Since the repositories are used for the build system, we wanted to be able to reliably `git pull` on master or the current RELEASE without the build system having to worry about merge conflicts. We also didn't want to expose ourselves to handling a raft of support questions about maintaining branches.

Your approach is basically what Bioconductor core team members do, maintaining various branches in github but pushing only master and current release to Bioconductor. Our remotes naming convention uses 'origin' for github, 'upstream' for bioconductor.

**Comment by gabora** [comment]
Thanks @mtmorgan  and @HenrikBengtsson for the discussion and comments!
I think the procedure is clear now.

**Comment by cokelaer** [comment]
I have now sent an email to packages at bioconductor asking for the changes.
